SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `client_request` (
  `ID` varchar(32) NOT NULL,
  `IP` varchar(19) DEFAULT NULL,
  `REQUEST_TIME` datetime DEFAULT NULL,
  `PROCESSING_TIME` bigint(20) DEFAULT NULL,
  `REQUEST_URL` varchar(4000) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `client_request_summary` (
  `ID` varchar(32) NOT NULL,
  `CLIENT_NUMBER` int(11) DEFAULT NULL,
  `CURRENT_DAY_NUMBER` int(11) DEFAULT NULL,
  `SUMMARY_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;