package com.cgodo.component.dao;

import com.cgodo.component.entity.WechatNotifyEntity;
import com.cgodo.component.entity.WechatNotifyEntityCondition;
import com.cgodo.component.model.WechatNotifyModel;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WechatNotifyEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    int countByExample(WechatNotifyEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    int deleteByExample(WechatNotifyEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    int insert(WechatNotifyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    int insertSelective(WechatNotifyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    List<WechatNotifyModel> selectByExampleWithRowbounds(WechatNotifyEntityCondition example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    List<WechatNotifyModel> selectByExample(WechatNotifyEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    WechatNotifyModel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WechatNotifyEntity record, @Param("example") WechatNotifyEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WechatNotifyEntity record, @Param("example") WechatNotifyEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WechatNotifyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WechatNotifyEntity record);
}