package com.cgodo.component.dao;

import com.cgodo.component.entity.WechatCallEntity;
import com.cgodo.component.entity.WechatCallEntityCondition;
import com.cgodo.component.model.WechatCallModel;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WechatCallEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_call
     *
     * @mbggenerated
     */
    int countByExample(WechatCallEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_call
     *
     * @mbggenerated
     */
    int deleteByExample(WechatCallEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_call
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_call
     *
     * @mbggenerated
     */
    int insert(WechatCallEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_call
     *
     * @mbggenerated
     */
    int insertSelective(WechatCallEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_call
     *
     * @mbggenerated
     */
    List<WechatCallModel> selectByExampleWithRowbounds(WechatCallEntityCondition example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_call
     *
     * @mbggenerated
     */
    List<WechatCallModel> selectByExample(WechatCallEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_call
     *
     * @mbggenerated
     */
    WechatCallModel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_call
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WechatCallEntity record, @Param("example") WechatCallEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_call
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WechatCallEntity record, @Param("example") WechatCallEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_call
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WechatCallEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_call
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WechatCallEntity record);
}