package com.cgodo.server.entity;

import com.cgodo.constant.EnumStatus;
import java.io.Serializable;
import java.util.Date;

public class ClientRequestSummaryEntity implements Serializable {
    private String id;

    /**
     * 状态
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private EnumStatus status;

    /**
     * 版本号
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private Long version;

    /**
     * 创建时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private Date gmtCreated;

    /**
     * 修改时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private Date gmtUpdated;

    /**
     * 总客户数，每次请求，都被视为一次统计
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private Integer clientNumber;

    /**
     * 当天客户数，每次新客户请求，都被视为一次统计
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private Integer currentDayNumber;

    /**
     * 统计当天时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private Date summaryTime;

    /**
     * 当天UV，按站点统计，即当天进入站点的人数(IP)
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private Integer uv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client_request_summary
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 状态
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public EnumStatus getStatus() {
        return status;
    }

    /**
     * 状态
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setStatus(EnumStatus status) {
        this.status = status;
    }

    /**
     * 版本号
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public Long getVersion() {
        return version;
    }

    /**
     * 版本号
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * 创建时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * 创建时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * 修改时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public Date getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * 修改时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setGmtUpdated(Date gmtUpdated) {
        this.gmtUpdated = gmtUpdated;
    }

    /**
     * 总客户数，每次请求，都被视为一次统计
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public Integer getClientNumber() {
        return clientNumber;
    }

    /**
     * 总客户数，每次请求，都被视为一次统计
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setClientNumber(Integer clientNumber) {
        this.clientNumber = clientNumber;
    }

    /**
     * 当天客户数，每次新客户请求，都被视为一次统计
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public Integer getCurrentDayNumber() {
        return currentDayNumber;
    }

    /**
     * 当天客户数，每次新客户请求，都被视为一次统计
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setCurrentDayNumber(Integer currentDayNumber) {
        this.currentDayNumber = currentDayNumber;
    }

    /**
     * 统计当天时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public Date getSummaryTime() {
        return summaryTime;
    }

    /**
     * 统计当天时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setSummaryTime(Date summaryTime) {
        this.summaryTime = summaryTime;
    }

    /**
     * 当天UV，按站点统计，即当天进入站点的人数(IP)
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public Integer getUv() {
        return uv;
    }

    /**
     * 当天UV，按站点统计，即当天进入站点的人数(IP)
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setUv(Integer uv) {
        this.uv = uv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_request_summary
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ClientRequestSummaryEntity other = (ClientRequestSummaryEntity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getGmtCreated() == null ? other.getGmtCreated() == null : this.getGmtCreated().equals(other.getGmtCreated()))
            && (this.getGmtUpdated() == null ? other.getGmtUpdated() == null : this.getGmtUpdated().equals(other.getGmtUpdated()))
            && (this.getClientNumber() == null ? other.getClientNumber() == null : this.getClientNumber().equals(other.getClientNumber()))
            && (this.getCurrentDayNumber() == null ? other.getCurrentDayNumber() == null : this.getCurrentDayNumber().equals(other.getCurrentDayNumber()))
            && (this.getSummaryTime() == null ? other.getSummaryTime() == null : this.getSummaryTime().equals(other.getSummaryTime()))
            && (this.getUv() == null ? other.getUv() == null : this.getUv().equals(other.getUv()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_request_summary
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getGmtCreated() == null) ? 0 : getGmtCreated().hashCode());
        result = prime * result + ((getGmtUpdated() == null) ? 0 : getGmtUpdated().hashCode());
        result = prime * result + ((getClientNumber() == null) ? 0 : getClientNumber().hashCode());
        result = prime * result + ((getCurrentDayNumber() == null) ? 0 : getCurrentDayNumber().hashCode());
        result = prime * result + ((getSummaryTime() == null) ? 0 : getSummaryTime().hashCode());
        result = prime * result + ((getUv() == null) ? 0 : getUv().hashCode());
        return result;
    }
}