package com.cgodo.component.entity;

import com.cgodo.constant.EnumStatus;
import com.cgodo.constant.EnumWechatNotifyType;
import java.io.Serializable;
import java.util.Date;

public class WechatNotifyEntity implements Serializable {
    private String id;

    /**
     * 状态
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private EnumStatus status;

    /**
     * 版本号
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private Long version;

    /**
     * 创建时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private Date gmtCreated;

    /**
     * 修改时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private Date gmtUpdated;

    /**
     * 回调参数
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private String params;

    /**
     * 处理结果
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private String result;

    /**
     * 回调类型
     *
     * @mbggenerated do_not_delete_during_merge
     */
    private EnumWechatNotifyType type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 状态
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public EnumStatus getStatus() {
        return status;
    }

    /**
     * 状态
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setStatus(EnumStatus status) {
        this.status = status;
    }

    /**
     * 版本号
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public Long getVersion() {
        return version;
    }

    /**
     * 版本号
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * 创建时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * 创建时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * 修改时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public Date getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * 修改时间
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setGmtUpdated(Date gmtUpdated) {
        this.gmtUpdated = gmtUpdated;
    }

    /**
     * 回调参数
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public String getParams() {
        return params;
    }

    /**
     * 回调参数
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * 处理结果
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public String getResult() {
        return result;
    }

    /**
     * 处理结果
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * 回调类型
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public EnumWechatNotifyType getType() {
        return type;
    }

    /**
     * 回调类型
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public void setType(EnumWechatNotifyType type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WechatNotifyEntity other = (WechatNotifyEntity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getGmtCreated() == null ? other.getGmtCreated() == null : this.getGmtCreated().equals(other.getGmtCreated()))
            && (this.getGmtUpdated() == null ? other.getGmtUpdated() == null : this.getGmtUpdated().equals(other.getGmtUpdated()))
            && (this.getParams() == null ? other.getParams() == null : this.getParams().equals(other.getParams()))
            && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_notify
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getGmtCreated() == null) ? 0 : getGmtCreated().hashCode());
        result = prime * result + ((getGmtUpdated() == null) ? 0 : getGmtUpdated().hashCode());
        result = prime * result + ((getParams() == null) ? 0 : getParams().hashCode());
        result = prime * result + ((getResult() == null) ? 0 : getResult().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        return result;
    }
}