package com.cgodo.member.dao;

import com.cgodo.member.entity.QqUserinfoEntity;
import com.cgodo.member.entity.QqUserinfoEntityCondition;
import com.cgodo.member.model.QqUserinfoModel;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface QqUserinfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_userinfo
     *
     * @mbggenerated
     */
    int countByExample(QqUserinfoEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_userinfo
     *
     * @mbggenerated
     */
    int deleteByExample(QqUserinfoEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_userinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_userinfo
     *
     * @mbggenerated
     */
    int insert(QqUserinfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_userinfo
     *
     * @mbggenerated
     */
    int insertSelective(QqUserinfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_userinfo
     *
     * @mbggenerated
     */
    List<QqUserinfoModel> selectByExampleWithRowbounds(QqUserinfoEntityCondition example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_userinfo
     *
     * @mbggenerated
     */
    List<QqUserinfoModel> selectByExample(QqUserinfoEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_userinfo
     *
     * @mbggenerated
     */
    QqUserinfoModel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_userinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QqUserinfoEntity record, @Param("example") QqUserinfoEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_userinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QqUserinfoEntity record, @Param("example") QqUserinfoEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_userinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QqUserinfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qq_userinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QqUserinfoEntity record);
}