package com.cgodo.member.dao;

import com.cgodo.member.entity.SinaUserinfoEntity;
import com.cgodo.member.entity.SinaUserinfoEntityCondition;
import com.cgodo.member.model.SinaUserinfoModel;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SinaUserinfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_userinfo
     *
     * @mbggenerated
     */
    int countByExample(SinaUserinfoEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_userinfo
     *
     * @mbggenerated
     */
    int deleteByExample(SinaUserinfoEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_userinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_userinfo
     *
     * @mbggenerated
     */
    int insert(SinaUserinfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_userinfo
     *
     * @mbggenerated
     */
    int insertSelective(SinaUserinfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_userinfo
     *
     * @mbggenerated
     */
    List<SinaUserinfoModel> selectByExampleWithRowbounds(SinaUserinfoEntityCondition example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_userinfo
     *
     * @mbggenerated
     */
    List<SinaUserinfoModel> selectByExample(SinaUserinfoEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_userinfo
     *
     * @mbggenerated
     */
    SinaUserinfoModel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_userinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SinaUserinfoEntity record, @Param("example") SinaUserinfoEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_userinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SinaUserinfoEntity record, @Param("example") SinaUserinfoEntityCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_userinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SinaUserinfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sina_userinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SinaUserinfoEntity record);
}